version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"  # Mapear el puerto configurado en .env
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"   # Mapea el puerto de PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: